name       : libxtst
version    : 1.2.3
release    : 11
source     :
    - https://www.x.org/releases/individual/lib/libXtst-1.2.3.tar.gz : a0c83acce02d4923018c744662cb28eb0dbbc33b4adc027726879ccf68fbc2c2
license    : MIT
component  : xorg.library
summary    : X11 Testing -- Record extension library
description: |
    libXtst provides an X Window System client interface to the Record extension to the X protocol.
optimize   : speed
emul32     : yes
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(xi)
    - pkgconfig32(x11)
    - pkgconfig(xproto)
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
