name        : libxtst
version     : 1.2.2
release     : 6
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXtst-1.2.2.tar.gz : 221838960c7b9058cd6795c1c3ee8e25bae1c68106be314bc3036a4f26be0e6c
license     :
    - MIT
summary     : X11 Testing -- Record extension library
component   : xorg.library
builddeps   :
    - pkgconfig(recordproto)
    - pkgconfig(inputproto)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(xi)
    - pkgconfig32(xi)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
optimize    : speed
emul32      : yes
patterns    :
    - devel:
        - /usr/share/man
description : |
    libXtst provides an X Window System client interface to the Record extension to the X protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
