name       : libxtst
version    : 1.2.3
release    : 10
source     :
    - https://www.x.org/releases/individual/lib/libXtst-1.2.3.tar.gz : a0c83acce02d4923018c744662cb28eb0dbbc33b4adc027726879ccf68fbc2c2
license    :
    - MIT
summary    : X11 Testing -- Record extension library
component  : xorg.library
builddeps  :
    - pkgconfig(recordproto)
    - pkgconfig(inputproto)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(xi)
    - pkgconfig32(xi)
    - pkgconfig(x11)
    - pkgconfig32(x11)
optimize   : speed
emul32     : yes
patterns   :
    - devel :
        - /usr/share/man
description: |
    libXtst provides an X Window System client interface to the Record extension to the X protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
